### Récupérer tous les secouristes
GET http://localhost:3000/rescuers

### Récupérer tous les secouristes disponibles
GET http://localhost:3000/rescuers/available

### Récupérer le secouriste d'id 1 (admin)
GET http://localhost:3000/rescuers/1


### Authentification admin
POST http://localhost:3000/authentification/login
Content-Type: application/json

{
    "email": "sstou.insa.projet@gmail.com",
    "password": "sslikenazis"
}

### Authentification rescuer
POST http://localhost:3000/authentification/login
Content-Type: application/json

{
    "email": "pierre-gilles.le_botlan@insa-cvl.fr",
    "password": "uniformpass"
}

### CHANGER LA VALEUR DU TOKEN (utile pour les requêtes suivantes)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNzdG91Lmluc2EucHJvamV0QGdtYWlsLmNvbSIsImlhdCI6MTY4NzIwMjUwNn0.b5MEtOADYFrB-jTw0A69p6F33wkj5f4QyLa-jra5Dio


### Créer un nouveau secouriste
POST http://localhost:3000/rescuers
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstname": "toto",
    "lastname": "billy",
    "email": "billytoto@gmail.com",
    "telephone": "",
    "disponibility": "",
    "password": "HM,fizllk:a"
}

### Recréer le même secouriste (échoue)
POST http://localhost:3000/rescuers
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstname": "toto",
    "lastname": "billy",
    "email": "billytoto@gmail.com",
    "telephone": "",
    "disponibility": "",
    "password": "HM,fizllk:a"
}

### Suppression d'un secouriste (changer l'id)
DELETE http://localhost:3000/rescuers/8
Authorization: Bearer {{token}}


### Recréation du secouriste supprimé
POST http://localhost:3000/rescuers
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstname": "toto",
    "lastname": "billy",
    "email": "billytoto@gmail.com",
    "telephone": "",
    "disponibility": "",
    "password": "HM,fizllk:a"
}

### Modification du secouriste
PATCH http://localhost:3000/rescuers/9
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "password": "Tibofssfssfec"
}


### Droit d'actions
DELETE http://localhost:3000/rescuers/9
Authorization: Bearer {{token}}
